### ISSUE TITLE
Cannot find module `@actions/core`

### ISSUE THREAD

**Issue by yamcodes** [rharkor/caching-for-turbo#34]
![CleanShot 2024-06-23 at 13 34 44@2x](https://github.com/rharkor/caching-for-turbo/assets/2014360/fa1655db-09d5-4ff5-8f02-29455a452398)

We're facing a bug when using this in one of our composite actions.

We've added the following step before `turbo build`:

```yml
    - name: Cache for Turbo
      uses: rharkor/caching-for-turbo@v1.2
```

And the issue prevented the workflow from completion in GitHub Actions.

**Comment by rharkor** [comment]
Hello,
Thank you for your issue. I fix this bug in the latest version (v1.3) https://github.com/rharkor/caching-for-turbo/pull/35

Also I wanted to thank you for the pull request helping me correcting my poor english level :joy:
